修正一些拼写错误。 1.AttributeError: module 'torch.serialization' has no attribute 'FILE_LIKE' 2.CosyVoiceModel changed cosyvoice.yaml to cosyvoice2.yaml 3.cached for robust_downloader.downloader - INFO - Downloading 4.Dockerfile ignore .git cause git report error in the config.py 5.RuntimeError: Cannot add middleware after an application has started. By: @self.app.middleware("http") 6.FireRedTts: Exception: Unknown model id: fireredtts in modules/core/pipeline/factory.py 7.The WebUI repeatly reports error when using CPU only: RuntimeError: Found no NVIDIA driver on your system. 8.Remap torch.load to device('cpu').
Signed-off-by: wang <w.limin@qq.com>